# spam classification 

In [47]:
# nlp practice 
# spam classification 
import pandas as pd 
mesge=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])



In [48]:
mesge

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [49]:
# data cleaning and preprocessing 
import re 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\madhu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [50]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [94]:
corpus=[]
for i in range(0,len(mesge)):
    review=re.sub('[^a-zA-Z]',' ',mesge['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [95]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [53]:
len(corpus)

5572

In [60]:
# out put features 
y=pd.get_dummies(mesge['label'],dtype='float')
y

,ham,spam
0,1.0,0.0
1,1.0,0.0
2,0.0,1.0
3,1.0,0.0
4,1.0,0.0
...,...,...
5567,0.0,1.0
5568,1.0,0.0
5569,1.0,0.0
5570,1.0,0.0


In [61]:
y=y.iloc[:,0].values

In [62]:
#train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [63]:
X_train

['so amount get pls',
 'ok lor early still project meeting',
 'one small prestige problem',
 'making easy pay back lt gt yr say pay back earlier get',
 'lol mad first woke gave',
 'anything',
 'thanx lot',
 'ok lor',
 'k head min see',
 'usual u call ard smth',
 'u reckon need arrange transport u thanks',
 'mum going robinson already',
 'bognor splendid time year',
 'would still cozy exhausted last night nobody went school work everything closed',
 'see shadow get early spring yay',
 'lol boo hoping laugh',
 'tot group mate lucky havent reply wat time need leave',
 'stop story told returned saying order',
 'problem baby good time talk called left message',
 'da run activate full version da',
 'life face choice toss coin becoz settle question coin air u know heart hoping gudni',
 'probably eat today think gonna pop weekend u miss',
 'r u cooking dinner',
 'call ok said call',
 'know called',
 'actually fuck whatever find excuse tampa point january though',
 'havent got da topic yet rite

In [64]:
len(X_train),len(y_train)

(4457, 4457)

In [65]:
# create BOW 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [66]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [67]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [68]:
from sklearn.naive_bayes import MultinomialNB
spmamodel=MultinomialNB().fit(X_train,y_train)

In [69]:
spmamodel

MultinomialNB()

In [70]:
y_pred=spmamodel.predict(X_test)


In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
classification_report(y_test,y_pred)
confusion_m=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)
print(confusion_m)
print(accuracy)
print(classification_report(y_test,y_pred))

[[136  11]
 [ 12 956]]
0.979372197309417
              precision    recall  f1-score   support

         0.0       0.92      0.93      0.92       147
         1.0       0.99      0.99      0.99       968

    accuracy                           0.98      1115
   macro avg       0.95      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [22]:
# test with new messages
#from textpreprocessing import preprocess_text
new_messages = ["Congratulations! You've won a free iPhone!", "Hey, are we still on for lunch tomorrow?"]
new_corpus=[]
for i in range(0,len(new_messages)):
    review=re.sub('[^a-zA-Z]',' ',new_messages[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    new_corpus.append(review)
    


In [ ]:
#test cleaning and preprocessing
# convert to vector using the same CountVectorizer
new_vectors = cv.transform(new_corpus).toarray()
new_vectors
y_pred = spmamodel.predict(new_vectors)
y_pred
# compare the predictions with the actual labels


array([0., 1.])

# TF-IDF

In [105]:
#train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [106]:
X_train

['reach ur home lt gt minute',
 'playin space poker u',
 'wait come lt gt min',
 'yes please leave lt gt lt gt leave',
 'yeah whatever lol',
 'aiyah wait lor u entertain hee',
 'k need login anything',
 'ur face test lt gt select number tell ur face astrology waiting quick reply',
 'yes obviously egg pert potato head speak soon',
 'late k wish',
 'pls confirm time collect cheque',
 'movie call wat',
 'urgent trying contact u today draw show prize guaranteed call land line claim valid hr',
 'tomarrow want got court lt decimal gt come bus stand',
 'home watching tv lor',
 'stuck da middle da row da right hand side da lt',
 'nice line said broken heart plz cum time infront wise trust u good',
 'cool tyler take gonna buy drop place later tonight total order quarter got enough',
 'hi roger cl',
 'ok lor msg b u call',
 'thing r good thanx got exam march ive done revision fran still boyf ive gotta interviw exeter bit worried x',
 'mths half price orange line rental latest camera phone free p

In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1,3))
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

In [108]:
tfidf.vocabulary_

{'reach': np.int64(1656),
 'ur': np.int64(2258),
 'home': np.int64(934),
 'lt': np.int64(1180),
 'gt': np.int64(824),
 'minute': np.int64(1294),
 'ur home': np.int64(2270),
 'lt gt': np.int64(1183),
 'gt minute': np.int64(832),
 'lt gt minute': np.int64(1190),
 'space': np.int64(1918),
 'wait': np.int64(2350),
 'come': np.int64(386),
 'min': np.int64(1281),
 'gt min': np.int64(831),
 'lt gt min': np.int64(1189),
 'yes': np.int64(2483),
 'please': np.int64(1535),
 'leave': np.int64(1093),
 'gt lt': np.int64(829),
 'lt gt lt': np.int64(1188),
 'gt lt gt': np.int64(830),
 'yeah': np.int64(2480),
 'whatever': np.int64(2406),
 'lol': np.int64(1140),
 'aiyah': np.int64(32),
 'lor': np.int64(1154),
 'hee': np.int64(893),
 'need': np.int64(1390),
 'login': np.int64(1137),
 'anything': np.int64(65),
 'face': np.int64(622),
 'test': np.int64(2058),
 'number': np.int64(1435),
 'tell': np.int64(2046),
 'waiting': np.int64(2352),
 'quick': np.int64(1631),
 'reply': np.int64(1702),
 'tell ur': np.in

In [109]:
from sklearn.naive_bayes import MultinomialNB
spmamodel=MultinomialNB().fit(X_train,y_train)

In [110]:
y_pred=spmamodel.predict(X_test)


In [111]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
classification_report(y_test,y_pred)
confusion_m=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)
print(confusion_m)
print(accuracy)
print(classification_report(y_test,y_pred))

[[132  30]
 [  1 952]]
0.9721973094170404
              precision    recall  f1-score   support

         0.0       0.99      0.81      0.89       162
         1.0       0.97      1.00      0.98       953

    accuracy                           0.97      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115

